// Generated by ResEdit 1.6.6
// Copyright (C) 2006-2015
// http://www.resedit.net

HINSTANCE hInst = GetModuleHandle(0);
WNDCLASSEX wcex;
ZeroMemory(&wcex, sizeof wcex);
wcex.cbSize         = sizeof wcex;
wcex.hbrBackground  = (HBRUSH)(COLOR_3DFACE + 1);
wcex.lpszMenuName   = 0;


wcex.style          = CS_HREDRAW | CS_VREDRAW;
wcex.lpfnWndProc    = DefWindowProc;
wcex.hInstance      = hInst;
wcex.hIcon          = LoadIcon(0, (LPCTSTR)IDI_APPLICATION);
wcex.hCursor        = LoadCursor(NULL, IDC_ARROW);
wcex.lpszClassName  = "WndClass0";
RegisterClassEx(&wcex);

HFONT hfont0 = CreateFont(-11, 0, 0, 0, 400, FALSE, FALSE, FALSE, 1, 400, 0, 0, 0, _T ("MS Shell Dlg"));
hWindow hWindow = CreateWindowEx (WS_EX_WINDOWEDGE | WS_EX_TOPMOST, _T ("WndClass")0, _T ("IO/Instructments"), WS_CAPTION | WS_SYSMENU, 0, 0, 332, 282, 0, 0, hInst, 0);
hWindow hCtrl0_0 = CreateWindowEx (0, WC_STATIC, _T ("Instructment"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 15, 55, 63, 16, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_0, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_1 = CreateWindowEx (0, WC_COMBOBOX, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_VSCROLL | CBS_DROPDOWNLIST | CBS_SORT, 87, 52, 222, 197, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_1, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_2 = CreateWindowEx (0, WC_BUTTON, _T ("Common Settings"), WS_VISIBLE | WS_CHILD | 0x00000007, 6, 5, 315, 244, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_2, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_3 = CreateWindowEx (0, WC_BUTTON, _T ("Open FeedBack Settings"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | 0x00000003, 15, 143, 143, 13, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_3, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_4 = CreateWindowEx (0, WC_STATIC, _T ("FixedVelocity"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 15, 83, 63, 16, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_4, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_5 = CreateWindowEx (WS_EX_STATICEDGE, WC_EDIT, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_NUMBER, 87, 80, 53, 20, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_5, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_6 = CreateWindowEx (0, WC_STATIC, _T ("&& 0x7F"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 143, 83, 39, 16, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_6, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_7 = CreateWindowEx (0, WC_BUTTON, _T ("add dls"), WS_VISIBLE | WS_CHILD | WS_TABSTOP, 186, 78, 123, 23, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_7, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_8 = CreateWindowEx (0, WC_STATIC, _T ("DLS collection"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 15, 24, 68, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_8, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_9 = CreateWindowEx (0, WC_COMBOBOX, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_VSCROLL | CBS_DROPDOWNLIST | CBS_SORT, 87, 23, 222, 197, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_9, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_10 = CreateWindowEx (0, WC_BUTTON, _T ("delcur dls"), WS_VISIBLE | WS_CHILD | WS_TABSTOP, 186, 109, 123, 23, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_10, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_11 = CreateWindowEx (WS_EX_STATICEDGE, WC_EDIT, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_NUMBER, 87, 111, 53, 20, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_11, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_12 = CreateWindowEx (0, WC_STATIC, _T ("OffsetNote"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 15, 114, 53, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_12, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_13 = CreateWindowEx (0, WC_STATIC, _T ("&& 0xFF"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 143, 114, 39, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_13, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_14 = CreateWindowEx (0, WC_STATIC, _T ("init_vel"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 186, 193, 35, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_14, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_15 = CreateWindowEx (WS_EX_STATICEDGE, WC_EDIT, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_NUMBER, 254, 189, 53, 20, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_15, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_16 = CreateWindowEx (0, WC_STATIC, _T ("max_vel"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 186, 223, 41, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_16, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_17 = CreateWindowEx (WS_EX_STATICEDGE, WC_EDIT, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_NUMBER, 254, 219, 53, 20, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_17, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_18 = CreateWindowEx (0, WC_STATIC, _T ("tomax_time"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 15, 223, 62, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_18, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_19 = CreateWindowEx (WS_EX_STATICEDGE, WC_EDIT, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_NUMBER, 87, 221, 53, 20, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_19, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_20 = CreateWindowEx (0, WC_STATIC, _T ("training_time"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 15, 193, 66, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_20, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_21 = CreateWindowEx (WS_EX_STATICEDGE, WC_EDIT, _T (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_NUMBER, 87, 192, 53, 20, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_21, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_22 = CreateWindowEx (0, WC_BUTTON, _T ("With Traning time"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | 0x00000003, 15, 166, 107, 13, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_22, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_23 = CreateWindowEx (0, WC_STATIC, _T ("ms"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 147, 193, 15, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_23, WM_SETFONT, (WPARAM)hFont, FALSE);
hWindow hCtrl0_24 = CreateWindowEx (0, WC_STATIC, _T ("ms"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 147, 224, 15, 15, hWindow, (HMENU)-1, hInst, 0);
SendMessage (hCtrl0_24, WM_SETFONT, (WPARAM)hFont, FALSE);
